export const DEBUG_LOG_OVERRIDE = false
export const DEBUG_LOG = false
export const PAGESTART = 'Library'
export const SERVER_DATABASE = '04'
export const NODE_ENV = 'production'
export const TIMEOUT = 1000
export const TIMEOUT_EXTRA = 1500
export const TIMEOUT_RETRY = 2
export const SERVER01 = 'onRender/3901'
export const DATABASE01 = 'Elephant1'
export const SERVERURL01 = 'https=//bridgeserver01.onrender.com'
export const SERVER02 = 'onRender/3902'
export const DATABASE02 = 'Railway02'
export const SERVERURL02 = 'https=//bridgeserver02.onrender.com'
export const SERVER03 = 'Cyclic/3903'
export const DATABASE03 = 'Elephant3'
export const SERVERURL03 = 'https=//bridgeserver03.cyclic.app'
export const SERVER04 = 'Cyclic/3904'
export const DATABASE04 = 'Railway04'
export const SERVERURL04 = 'https=//bridgeserver04.cyclic.app'
export const SERVER11 = '3911'
export const SERVERURL11 = 'http=//localhost=3911'
export const SERVER12 = '3912'
export const SERVERURL12 = 'http=//localhost=3912'
export const SERVER13 = '3913'
export const SERVERURL13 = 'http=//localhost=3913'
export const SERVER14 = '3914'
export const SERVERURL14 = 'http=//localhost=3914'
export const SERVER16 = '3916'
export const DATABASE6 = 'http=//localhost=3916'
export const SERVERURL16 = 'bridge06'
export const SERVER17 = '3917'
export const DATABASE7 = 'http=//localhost=3917'
export const SERVERURL17 = 'bridge07'
export const DFT_USER_MAXQUESTIONS = 20
export const DFT_USER_OWNER = 'NZBridge'
export const DFT_USER_SHOWPROGRESS = true
export const DFT_USER_SHOWSCORE = true
export const DFT_USER_SORTQUESTIONS = true
export const DFT_USER_SKIPCORRECT = true
export const URL_HELLO = '/QuizHello'
export const URL_REGISTER = '/QuizRegister'
export const URL_REGISTERPWD = '/QuizRegisterPwd'
export const URL_SIGNIN = '/QuizSignin'
export const URL_TABLES = '/QuizTables'
export const BACKGROUNDCOLOR_TABLEPAPER = 'lightyellow'
export const BACKGROUNDCOLOR_TABLEHEAD = 'lightblue'
export const BACKGROUNDCOLOR_TABLEBODY = 'lightgreen'
export const BACKGROUNDCOLOR_MYINPUT = 'azure'
export const BACKGROUNDCOLOR_PAGEHEAD = 'sandybrown'
export const BACKGROUNDCOLOR_FORMPAPER = 'whitesmoke'
export const BACKGROUNDCOLOR_NAVBAR = 'green'
export const BACKGROUNDCOLOR_MYINPUTDISABLED = 'lightpink'
