export const DEBUG_LOG_OVERRIDE = false
export const DEBUG_LOG = false
export const PAGESTART = 'Library'
export const SERVER_DATABASE = '04'
export const NODE_ENV = 'production'
export const TIMEOUT = 1000
export const TIMEOUT_EXTRA = 1500
export const TIMEOUT_RETRY = 2
export const SERVER01 = 'REMOTE=Render/3901'
export const DATABASE01 = 'REMOTE-1=Elephant'
export const SERVERURL01 = 'https=//bridgeSERVER01.onrender.com'
export const SERVER02 = 'REMOTE=Render/3902'
export const DATABASE02 = 'REMOTE-2=Railway'
export const SERVERURL02 = 'https=//bridgeSERVER02.onrender.com'
export const SERVER03 = 'REMOTE=Cyclic/3903'
export const DATABASE03 = 'REMOTE-3=Elephant'
export const SERVERURL03 = 'https=//bridgeserver03.cyclic.app'
export const SERVER04 = 'REMOTE=Cyclic/3904'
export const DATABASE04 = 'REMOTE-4=Railway04'
export const SERVERURL04 = 'https=//bridgeserver04.cyclic.app'
export const SERVER11 = 'LOCAL=3911'
export const SERVERURL11 = 'http=//localhost=3911'
export const SERVER12 = 'LOCAL=3912'
export const SERVERURL12 = 'http=//localhost=3912'
export const SERVER13 = 'LOCAL=3913'
export const SERVERURL13 = 'http=//localhost=3913'
export const SERVER14 = 'LOCAL=3914'
export const SERVERURL14 = 'http=//localhost=3914'
export const SERVER16 = 'LOCAL=3916'
export const DATABASE6 = 'http=//localhost=3916'
export const SERVERURL16 = 'LOCAL=bridge6'
export const SERVER17 = 'LOCAL=3917'
export const DATABASE7 = 'http=//localhost=3917'
export const SERVERURL17 = 'LOCAL=bridge7'
export const DFT_USER_MAXQUESTIONS = 20
export const DFT_USER_OWNER = 'NZBridge'
export const DFT_USER_SHOWPROGRESS = true
export const DFT_USER_SHOWSCORE = true
export const DFT_USER_SORTQUESTIONS = true
export const DFT_USER_SKIPCORRECT = true
export const URL_HELLO = '/QuizHello'
export const URL_REGISTER = '/QuizRegister'
export const URL_REGISTERPWD = '/QuizRegisterPwd'
export const URL_SIGNIN = '/QuizSignin'
export const URL_TABLES = '/QuizTables'
